name: app_rental
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.0.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  flutter_svg : ^2.0.10+1
  sqflite: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.2
  flutter_slidable: ^3.1.0
  google_fonts: 6.1.0
  image_picker: ^1.0.8
  flutter_bloc: ^8.1.5
  meta: ^1.10.0
  intl: ^0.19.0
  animate_do: ^3.3.4
  flutter_secure_storage: ^9.2.2
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.14.2  # Pastikan dependensi ini ada di sini

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"  # Pastikan path ini benar

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/boarding.jpg
    - assets/detail.jpg
    - assets/home.jpg
    - assets/diskon.png
    - assets/icon/icon.png  # Pastikan path ini sesuai dengan folder dan file yang ada
